### ISSUE TITLE
Missing product details when queried using the GetProductsByCollectionId

### ISSUE THREAD

**Issue by xuala69** [ThinkSimple/flutter_simple_shopify#13]
As the given title, product details like price,discount are not returned

**Comment by xuala69** [comment]
Bit too deep inside and had to go through everything to get it. sorry for any inconvenience caused. 

ps: it's inside the variant if anyone else finds it hard to see it

**Comment by ThinkSimple** [comment]
Hey, Shopify chose to show the price **range** if you look at a product, the price range consists of the lowest variant price up to the highest one.
Which makes sense, because the variants contain the exact prices.

greetings, adam.

**Comment by xuala69** [comment]
Hi Adam,

Thanks for the clarification. However, I'm running into another problem not related to this issue, but I can't seem to find any documentation on how to complete  a checkout operation. I see a "completeCheckoutVisa" and "completeCheckoutFree" mutation strings inside the graphql_operations folder and yet they aren't usable for the package user as ShopifyCheckout.instance doesn't have any methods like that to call  or am I missing something (again xD). 

Thanks

**Comment by ThinkSimple** [comment]
Hey, this is probably the most frustrating part.
Back in the development of this package we thought it was possible to
create your own checkout but after trying and asking the shopify staff we
could not get a answer on how to use these mutations, that is why we simply
implemented a webview inside our own app.
There does not seem to be a purpose for these mutations or at least we can
not find one.
I recommend that you get the url from the checkout and redirect to a
webview.

Greetings, Adam from ThinkSimple.

**Comment by xuala69** [comment]
Thank you again for the clarification Adam. You've been way more helpful than google these past few days :D

Have a great day and Thanks again
