### ISSUE TITLE
Add #hacktoberfest topic

### ISSUE THREAD

**Issue by tuarrep** [ThinkSimple/flutter_simple_shopify#18]
It's Hacktoberfest this month https://hacktoberfest.digitalocean.com/

Due to spam, maintainers need to manually add hactoberfest topic to repositories.

Could you please add it? This could attract devs to the repo during the month of October

**Comment by ThinkSimple** [comment]
Hey, added, thank you!

**Comment by ThinkSimple** [comment]
Thank you for your contribution to the package Nicolas!

Adam from ThinkSimple.
