### ISSUE TITLE
flutter: Exception: GraphQL Errors: access denied: Undefined location

### ISSUE THREAD

**Issue by cafe99** [ThinkSimple/flutter_simple_shopify#2]
Hi all the expert,

  I'm new to this, when I do the testing on the flutter_simple_shopify example on my MacBook running Visual Stdio Code, I got this error:

		flutter: Exception: GraphQL Errors:
		access denied: Undefined location

======================

Launching lib/main.dart on iPhone 8 Plus in debug mode...
Xcode build done.                                           69.0s
Connecting to VM Service at ws://127.0.0.1:52642/S1Vp1HqL3FQ=/ws
flutter: Exception: GraphQL Errors:
access denied: Undefined location
flutter: Exception: GraphQL Errors:
access denied: Undefined location

+++++++++++++++++++++=

======================
    Need your help..  Thanks.

Choong Leng from Singapore
coffee@tradx.asia

**Comment by ThinkSimple** [comment]
Hello,
could you provide some of your source code?
And tell us, when exactly this happens?

**Comment by cafe99** [comment]
> Hello,
> could you provide some of your source code?
> And tell us, when exactly this happens?

Hi, I create a new project : 
  
> flutter create --org com.cfxsg shopify
> cd shopify
> cp /tmp/flutter_simple_shopify/example/lib ./lib
> cp /tmp/flutter_simple_shopify/pubspec.yaml .

modify the main.dart 
==========
void main() {
  ShopifyConfig.setConfig(
    "7682f0bcf00f909b3bd3bb5edxxxxxxxx",
    "cfx-market.myshopify.com",
    "2020-04",
  );
  runApp(MyApp());
}
============
then I run under the debug mode...

Launching lib/main.dart on iPhone 8 Plus in debug mode...
Xcode build done. 69.0s
Connecting to VM Service at ws://127.0.0.1:52642/S1Vp1HqL3FQ=/ws
flutter: Exception: GraphQL Errors:
access denied: Undefined location
flutter: Exception: GraphQL Errors:
access denied: Undefined location

**Comment by ThinkSimple** [comment]
Do you have all access scopes for the storefront api activated? 
You activate them by going on apps -> manage private apps -> "your private app" and tick all boxes at the bottom

**Comment by cafe99** [comment]
Thanks for the help. 

Ok, Issue solve: this at the manage private apps : must tick the following,
    Read product tags
    unauthenticated_read_product_tags

    Read inventory of products and their variants
    unauthenticated_read_product_inventory

**Comment by ThinkSimple** [comment]
Glad to help.

Greetings, Adam from Thinksimple.
