### ISSUE TITLE
Issue on orders get 

### ISSUE THREAD

**Issue by popiosifcristian** [ThinkSimple/flutter_simple_shopify#24]
Hello,
I'm trying to get all orders from an user, but only thing that I receive is an error. I've posted below the error and also the code that I use on receiving the orders. Is this a bug or I am doing anything wrong?

error: `GraphQL Errors:
Internal error. Looks like something went wrong on our end.
Request ID: 0835140f-3150-4dd1-950d-718d002d998a (include this in support requests).: Undefined location`

code: `await ShopifyCheckout.instance
        .getAllOrders(await ShopifyAuth.currentCustomerAccessToken)`

Thank you for your work on this library!

Kind regards,
Iosif

**Comment by ThinkSimple** [comment]
Hey, will try to look into it in the next few days.

**Comment by ThinkSimple** [comment]
Have you tried hard coding the customerAccessToken and not awaiting it?
Just print the customerAccessToken and insert it to the getAllOrders function as the param.
Or save the **await ShopifyAuth.currentCustomerAccessToken** to a variable before and execute it again with the usage of the variable.

**Comment by popiosifcristian** [comment]
Hello, sorry for the late response. The issue still persists. Have you checked on your end if this functionallity still works? It may also be an issue on shopify side. I'm currently using an development store but I gave full permissions on api to my shopify private app.

**Comment by ThinkSimple** [comment]
Hey, sorry that it took quite a while, the problem seems to be a **really** dumb one.
The problem is most likely the sort key, the Shopify api allows the RELEVANCE sortkey but somehow it doesn't work with it.
I tried the exact same query now 1. with sortkey: PROCESSED_AT and 2. with sorkey: RELEVANCE.
The processed at sortkey works, long story short try changing the sortkey.

**Comment by popiosifcristian** [comment]
Hey, no worries for the late response. I have just tested it and it works, changing the sortkey did the trick! Thanks a lot!
