### ISSUE TITLE
[Question Customer] Add first name and lastname

### ISSUE THREAD

**Issue by AgustinOliver98** [ThinkSimple/flutter_simple_shopify#26]
I have a registration form with:

Name, surname, email and password

Is it possible to create a customer email and password and add the first and last name?

```
 try {
      var user = await _authService.createUserWithEmailAndPassword(
          email: email, password: password);
      await ShopifyCustomer.instance.customerUpdate(
        customerAccessToken: ShopifyAuth.currentCustomerAccessToken,
        firstName: firstName,
        lastName: lastName,
      );
      _token = await ShopifyAuth.currentCustomerAccessToken;
      notifyListeners();
    }

```

**Comment by ThinkSimple** [comment]
Hey Agustin, the use case you described should be possible, ist your code not working?

**Comment by AgustinOliver98** [comment]
The use case it's to register a customer with first name and lastname. I can solve it by doing this : 

```
var user = await _authService.createUserWithEmailAndPassword(
          email: email, password: password);
      _token = await ShopifyAuth.currentCustomerAccessToken;
      await ShopifyCustomer.instance.customerUpdate(
        customerAccessToken: _token,
        firstName: firstName,
        lastName: lastName,
      );
      await ShopifyAuth.instance
          .signInWithEmailAndPassword(email: email, password: password);
```

**Comment by ThinkSimple** [comment]
The code is working for me.
I am not sure where the problem is

**Comment by AgustinOliver98** [comment]
Yes, it works without problems! I have an other question
Is it possible to search for products using multiple filters?
For example: give me the products of collection A and B and for this price range

I'm trying to make that query  but I dont understand how to do it

**Comment by AgustinOliver98** [comment]
I already solve the query! Sorry to bother. Thanks, amazing package
