### ISSUE TITLE
ShopifyConfig.setConfig reset not working properly

### ISSUE THREAD

**Issue by zhihaozhang** [ThinkSimple/flutter_simple_shopify#3]
ShopifyConfig.setConfig works only for the first time, how can I reset the config?

**Comment by ThinkSimple** [comment]
You mean, whether you change the configs, it is still always the first store that you typed in that pops up?

**Comment by ThinkSimple** [comment]
I tried to find a workaround but I can't seem to find any, since this is wanted behaviour.
I can't seem to find a solution to fit such an use can.
If I find a free day, I will test some more.
