### ISSUE TITLE
'shopifyCheckout.checkoutCompleteFree' returns unclear error

### ISSUE THREAD

**Issue by emvaized** [ThinkSimple/flutter_simple_shopify#32]
Here's the code I'm using:
```
String checkoutId = await shopifyCheckout.createCheckout();
await shopifyCheckout.checkoutLineItemsReplace(checkoutId, _checkoutItems);
await shopifyCheckout.checkoutCustomerAssociate(checkoutId, _accessToken);
await shopifyCheckout.checkoutDiscountCodeApply(checkoutId, _discountCode);
await shopifyCheckout.checkoutCompleteFree(checkoutId);
```
The last line throws a `CheckoutCompleteException`:
`message` of this exception just says `Error on checkoutCompleteFree`,
and `errors` node returns list of instances of `LazyCacheMap`

**Comment by emvaized** [comment]
Alright, wrapping code in:
```
try {
...
} catch (error) {
  error.errors.forEach((error) => print(error.data));
}
```
gave my errors from Shopify on why checkout was rejected. I think this check must be included in the `checkoutCompleteFree` method itself, so that the exception is more clear.

**Comment by ThinkSimple** [comment]
So you mean that you feel that iterating through the errors is unnecessary and that it should be automatically printed?

**Comment by emvaized** [comment]
@ThinkSimple I mean that it's not clear at all what kind of iteration needed without diving in the sources, as just calling "checkoutCokoleteFree" method returns just "Error on checkoutCompleteFree"

**Comment by ThinkSimple** [comment]
I believe i fixed it now, the errors get printed directly for a more cleare understanding, there is no more need to iterate through the errors.
(Will upload in next update, which should actually be today)

**Comment by newdeveloper15** [comment]
hi, 
i am getting this error after calling checkoutCompleteFree() 

 {code: MISSING_PAYMENT_INPUT, field: null, message: Checkout requires payment.}

Any idea how to resovle this ?
