### ISSUE TITLE
Getting {code: MISSING_PAYMENT_INPUT, field: null, message: Checkout requires payment.} error in checkoutCompleteFree - Utilizing this for Cash on Delivery 

### ISSUE THREAD

**Issue by monishblue** [ThinkSimple/flutter_simple_shopify#33]
Steps i follow to checkout 

String checkoutId = await shopifyCheckout.createCheckout();
await shopifyCheckout.checkoutLineItemsReplace(
          checkoutId, checkoutLineItems); // Line items is  Product Variant Id
await shopifyCheckout.shippingAddressUpdate(checkoutId, address1, address2, company, city, country, firstName, lastName, phone, province, zip);
await shopifyCheckout.checkoutCompleteFree(checkoutId);

is Throwing error 

 {code: MISSING_PAYMENT_INPUT, field: null, message: Checkout requires payment.} error in checkoutCompleteFree

Note: -- Utilizing this for Cash on Delivery

Please Help!

**Comment by ThinkSimple** [comment]
I believe the Storefront API does not support cash on delivery, have you searched the web for an answer?

**Comment by monishblue** [comment]
Yes finally done with help of node Admin API.. Thanks for providing this!!
