### ISSUE TITLE
createUserWithEmailAndPassword() does not take first name and last name 

### ISSUE THREAD

**Issue by moiye-dev** [ThinkSimple/flutter_simple_shopify#34]
Its not possible to set  first name and last name in  function createUserWithEmailAndPassword(). How can I associate a users name upon registration?

**Comment by hetkpatel** [comment]
You can use the `customerUpdate()` method within the `ShopifyCustomer` class after `createUserWithEmailAndPassword()`. Unfortunately, there is no single create customer method with the ability to associate name with user creation.

```
await auth.createUserWithEmailAndPassword(email: _email, password: _password);

ShopifyCustomer customer = ShopifyCustomer.instance;
await customer.customerUpdate(firstName: _firstName, lastName: _lastName);
```

Might need to do some string split to extract first and last names.

**Comment by moiye-dev** [comment]
Thanks that should work. 
Best regards 
Saurabh

**Comment by ThinkSimple** [comment]
Im assuming that it works.
