### ISSUE TITLE
There is no variables in Create Checkout

### ISSUE THREAD

**Issue by dineshkick** [ThinkSimple/flutter_simple_shopify#37]
How to provide the VariantId and quantity in createCheckout() method

**Comment by emvaized** [comment]
Hi @dineshkick 
I faced this issue too, and spent a few days figuring it out. Here's basically the code you should use, where `_checkoutItems` is a list of VariantId strings.

```
 String checkoutId = await shopifyCheckout.createCheckout();
await shopifyCheckout.checkoutLineItemsReplace(checkoutId, _checkoutItems);
```

**Comment by dineshkick** [comment]
Thanks for the reply. In the _checkoutItems what i want to send... Variant ID of that product or ?!

**Comment by emvaized** [comment]
@dineshkick 
Yes, a list of VariantIDs strings.

**Comment by ThinkSimple** [comment]
Closing issue, please create a new issue if needed.
