### ISSUE TITLE
[Issue] 'customerAddressCreate' and 'customerAddressUpdate' do no effect

### ISSUE THREAD

**Issue by emvaized** [ThinkSimple/flutter_simple_shopify#39]
Both method execute with no exceptions, but profile addresses on the website are not updated.

**Comment by moiye-dev** [comment]
I am also having problems with customerAddressCreate. At times it works and mostly fails silently.

**Comment by SimonIT** [comment]
I addressed recently the problem with silent errors in b459a828d5406f94c80de8a784118670a92142cf. If you use the version from master it should be better

**Comment by moiye-dev** [comment]
> I addressed recently the problem with silent errors in [b459a82](https://github.com/ThinkSimple/flutter_simple_shopify/commit/b459a828d5406f94c80de8a784118670a92142cf). If you use the version from master it should be better

Thank you so much!
Now I see the cause of the problem after your change - Province is not valid! 
best regards

**Comment by SimonIT** [comment]
I'm closing it for now because of no response from the original author.
If the issue does still persist, feel free to leave a comment and I will reopen the issue :)
