### ISSUE TITLE
Webview using  the checkout object's  webUrl displays empty Shipping Address section.

### ISSUE THREAD

**Issue by moiye-dev** [ThinkSimple/flutter_simple_shopify#50]
The checkout function I wrote along the lines below:

================
    

    ShopifyCheckout shopifyCheckout = ShopifyCheckout.instance;
    String checkoutId = await shopifyCheckout.createCheckout();

   
    //Adds all product variants 
    List<String> variants = List();
    cartItems.forEach((item) => {
          for (var _ in Iterable<int>.generate(item.quantity).toList())
            {variants.add(item.variantId)}
        });

    await shopifyCheckout.checkoutLineItemsReplace(checkoutId, variants);

    String token = (await SharedPreferences.getInstance())
        .getString('FLUTTER_SIMPLE_SHOPIFY_ACCESS_TOKEN');

    await shopifyCheckout.checkoutCustomerAssociate(checkoutId, token,
        deleteThisPartOfCache: true);

    Checkout checkout = await shopifyCheckout.getCheckoutInfoQuery(checkoutId,
        deleteThisPartOfCache: true);
     
     //Use checkout.webUrl in Webview ...

==================

The WebView displays the order summary correctly but the Shipping  address fields are empty (First Name, Last name, address, etc... are all empty) despite the fact that the checkout is associated with a valid logged-in users access token.

Thanks for an amazing library!

<img width="457" alt="Screenshot 2021-01-16 at 1 48 46 AM" src="https://user-images.githubusercontent.com/61445679/104761139-67546c00-579d-11eb-9038-5f0f3c77bbf4.png">

**Comment by SimonIT** [comment]
From my experience this is the result of a missing or invalid parameter of the address. If you look into the response of like I did in #52 you will probably find the problem

**Comment by moiye-dev** [comment]
Thanks! I now provided a complete set of address params and it works like a charm. Sample code below:

await ShopifyCheckout.instance.shippingAddressUpdate(
        checkoutId,
        address.address1,
        address.address2,
        address.company,
        address.city,
        address.country,
        address.firstName,
        address.lastName,
        address.phone,
        address.province,
        address.zip);
    Checkout ref = await ShopifyCheckout.instance
        .getCheckoutInfoQuery(checkoutId, deleteThisPartOfCache: true);
    displayPaymentView(ref,` widget.cart);

**Comment by patricknicolosi** [comment]
@moiye-dev Can you send a more complete example?

How should I use this

`await ShopifyCheckout.instance.shippingAddressUpdate(
checkoutId,
address.address1,
address.address2,
address.company,
address.city,
address.country,
address.firstName,
address.lastName,
address.phone,
address.province,
address.zip);
Checkout ref = await ShopifyCheckout.instance
.getCheckoutInfoQuery(checkoutId, deleteThisPartOfCache: true);`

in this?:

`ShopifyCheckout shopifyCheckout = ShopifyCheckout.instance;
String checkoutId = await shopifyCheckout.createCheckout();


//Adds all product variants 
List<String> variants = List();
cartItems.forEach((item) => {
      for (var _ in Iterable<int>.generate(item.quantity).toList())
        {variants.add(item.variantId)}
    });

await shopifyCheckout.checkoutLineItemsReplace(checkoutId, variants);

String token = (await SharedPreferences.getInstance())
    .getString('FLUTTER_SIMPLE_SHOPIFY_ACCESS_TOKEN');

await shopifyCheckout.checkoutCustomerAssociate(checkoutId, token,
    deleteThisPartOfCache: true);

Checkout checkout = await shopifyCheckout.getCheckoutInfoQuery(checkoutId,
    deleteThisPartOfCache: true);
 
 //Use checkout.webUrl in Webview ...`

**Comment by moiye-dev** [comment]
Basically create a checkout object using the first snippet I attached in the issue and then allow a user to select a shipping address in UI which then is associated  (using the second snippet) with the newly created checkout.
