### ISSUE TITLE
customerUpdate() doesn't update user field 

### ISSUE THREAD

**Issue by mostafaAbdelazim** [ThinkSimple/flutter_simple_shopify#62]
Hi there, Thanks for putting the time and effort on this awesome package.

I've been trying to update customer data via this code 

`      await ShopifyCustomer.instance.customerUpdate(
          customerAccessToken: await ShopifyAuth.currentCustomerAccessToken,
          firstName: user.firstName,
          lastName: user.lastName,
          email: user.email,
          phoneNumber: user.phoneNumber);`
          
but when i try to retrieve the current user via this code 

`      ShopifyUser shopifyUser = await ShopifyAuth.instance.currentUser();`
it returns a user object with the old values, is this some sort of caching issue ?

**Comment by SimonIT** [comment]
I addressed recently the problem with silent errors in b459a828d5406f94c80de8a784118670a92142cf. If you use the version from master it should be better to find the problem

**Comment by SimonIT** [comment]
I'm closing it for now because of no response from the original author.
If the issue does still persist, feel free to leave a comment and I will reopen the issue :)
