### ISSUE TITLE
How to complete full checkout process?

### ISSUE THREAD

**Issue by rajubd49** [ThinkSimple/flutter_simple_shopify#67]
Hi,

I'm using this Flutter package for my application to use Shopify. I was able to load, search Products using this package but was unable to complete the full checkout process. What I tried so far is, 

```
      ShopifyCheckout shopifyCheckout = ShopifyCheckout.instance;
      String checkoutId = await shopifyCheckout.createCheckout();
      List<String> variantIdList = List();
      order.orderlines
          .forEach((orderline) => {variantIdList.add(orderline.itemBarcode)});
      try {
        await shopifyCheckout.checkoutLineItemsReplace(
            checkoutId, variantIdList);
        Checkout checkout =
            await shopifyCheckout.getCheckoutInfoQuery(checkoutId);
        print(checkout.webUrl);
      } catch (e) {
        print(e.toString());
      }
```

What is does is it provide me the correct product checkout weburl, but on that url I saw that my product quantity was always shows as 1, how can I define the quantity using this package?

**Comment by SimonIT** [comment]
You have to add your variant ids multiples times to your `variantIdList` for `checkoutLineItemsReplace`

**Comment by rajubd49** [comment]
I understand and get the result that you explain. But the scenario is for example, I can have 100 items(orderline in my case) with quantities like 30, 40, 50 etc in my cart(order in my case). So wouldn't it be much better if we can define the quantity for each item? 

In iOS Shopify package I used, there I can add both quantity and item number like below, my question was is there any we can do the same here and if not can we have feature like this?

```
            let lineItems = order.orderlines.map { orderline in
                Storefront.CheckoutLineItemInput.create(quantity: Int32(orderline.quantityOrdered), variantId: GraphQL.ID(rawValue: orderline.itemBarcode))
            }
    
            let checkoutInput = Storefront.CheckoutCreateInput.create(
                lineItems: .value(lineItems),
                allowPartialAddresses: .value(true)
            )
    
            let mutation =  Storefront.buildMutation { $0
                .checkoutCreate(input: checkoutInput) { $0
                    .checkout { $0
                        .fragmentForCheckout()
                    }
                }
            }
            let task = Client.shared.client.mutateGraphWith(mutation) { response, error in
                if let weburl = response?.checkoutCreate?.checkout?.webUrl {
                    print(weburl.absoluteString)
                }
            }
            task.resume()

```
 I know iOS library is maintained by Shopify and I really appreciate that you guys is maintaining this package well enough.

**Comment by SimonIT** [comment]
I would totally be possible because the list with the ids gets transformed into a map like you described:

https://github.com/ThinkSimple/flutter_simple_shopify/blob/c625da666f80a77372942ee19be2380452a835dc/lib/shopify/src/shopify_checkout.dart#L117-L130

https://github.com/ThinkSimple/flutter_simple_shopify/blob/c625da666f80a77372942ee19be2380452a835dc/lib/shopify/src/shopify_checkout.dart#L151-L162
