### ISSUE TITLE
Sorting Collection by 'CREATED' returns the query sorted by oldest instead of newest

### ISSUE THREAD

**Issue by emvaized** [ThinkSimple/flutter_simple_shopify#7]
Here's the method I'm using to fetch:
```
allProducts = await shopifyStore.getXProductsAfterCursorWithinCollection(
      _collection.id,
      24,
      null,
      sortKey: SortKeyProductCollection.CREATED,
    );
```

Would be nice to see the query sorted by 'newest' instead.
The same goes for the 'PRICE' sorting - would be nice to have 2 options.

Version: 0.18

**Comment by ThinkSimple** [comment]
I believe that is the default behavior from shopify, is there an optional parameter "reverse"?
If yes please use it, it basically just reverses the whole list.

**Comment by emvaized** [comment]
@ThinkSimple 
Thanks! Problem solved.
