### ISSUE TITLE
Can not get variant id (int) product

### ISSUE THREAD

**Issue by hautran90** [ThinkSimple/flutter_simple_shopify#72]
I'm building a project that uses Shopify. But I have a problem, the variant id of the product is a String and not an int. I need a variant id of type int to use for checkout. Please help me. Thanks!

![image](https://user-images.githubusercontent.com/40556511/119626166-1fbdab00-be35-11eb-8ad2-025a95041887.png)
![image](https://user-images.githubusercontent.com/40556511/119624917-d4ef6380-be33-11eb-91b4-d71a960e513b.png)

**Comment by SimonIT** [comment]
What do you want to do with the variant id?
If you want to add them to the checkout use this method:
`ShopifyCheckout.instance.checkoutLineItemsReplace`
