### ISSUE TITLE
ShopifyUser.id and Product.id return hashed values

### ISSUE THREAD

**Issue by Unown-Fashion** [ThinkSimple/flutter_simple_shopify#8]
`ShopifyAuth.currentUser().id` returns a 48-digit value in format `Z2lkOi8vc2hvcGlmeS9DdXN0b21lci8yMTM2NTg0NDIxNDU4`, while fetching it with Liquid on site returns `2136584421458`.

The question is - how to programmatically get second value from the first?
Didn't found any information about this in Shopify's API documentation.

**Comment by ThinkSimple** [comment]
I can't think of why that is, what are you trying to achieve exactly?
Will take a closer look on tuesday.

**Comment by Unown-Fashion** [comment]
@ThinkSimple 
Thanks!
I think it seems like `ShopifyAuth.currentUser().id` somehow returns hashed value, because customer's id in the Shopify itself is being stored like that: `2136584421458`.

I've noticed the same behavior for the `Product.id` - it returns 48-digit value which looks hashed, instead of 13-digit ids which can be seen from admin's console for each product.

**Comment by ThinkSimple** [comment]
Hey I've looked into their docs but I can not find why that is like that, you might be better off with your question in their [forum](https://community.shopify.com/c/Shopify-Community/ct-p/en)
I would also advise you to describe your use case since they may help you find a workaround.

**Comment by Unown-Fashion** [comment]
@ThinkSimple 
I've looked into it, and found the exact issue I face: 
[https://community.shopify.com/c/Storefront-API-SDKs/Wha-is-the-difference-between-customer-Id-in-store-front-and/m-p/699881](https://community.shopify.com/c/Storefront-API-SDKs/Wha-is-the-difference-between-customer-Id-in-store-front-and/m-p/699881)

And here's [suggested solution](https://community.shopify.com/c/Shopify-APIs-SDKs/Storefront-API-variantId-different-than-Rest-API-variantId/m-p/607815#M41290), which I guess requires modifying request to Starefront API.

**Comment by ThinkSimple** [comment]
Hey, thanks for the link, after scrolling through some answers this seems to work:

Codec<String, String> stringToBase64 = utf8.fuse(base64);
String test = stringToBase64.decode('Z2lkOi8vc2hvcGlmeS9DdXN0b21lci8yMTM2NTg0NDIxNDU4');
print(test);
// expected output: gid://shopify/Customer/2136584421458

Now you would only need to get id from the string
