### ISSUE TITLE
How to open  Shopify checkout and payment options by clicking a buy button in an application?

### ISSUE THREAD

**Issue by navidanchitrali** [ThinkSimple/flutter_simple_shopify#84]
I can't fully understand the check out functions. Can someone please provide me  the code or functions, which are available in this package to perform the functionality I want?

Or ideas on how to do this Please?

**Comment by SimonIT** [comment]
You basically create a checkout with `ShopifyCheckout.instance.createCheckout`. This returns a checkoutId as string. With that you can use the other methods to assign a user, line items etc. Then you can get the infos with `ShopifyCheckout.instance.getCheckoutInfoQuery`  and complete the checkout for example with a webview `WebView(
                        initialUrl: _checkout.webUrl,
`.

**Comment by navidanchitrali** [comment]
thanks sir, i will try it and let you know if something gone wrong :)

**Comment by navidanchitrali** [comment]
@SimonIT  Sir , what is _checkout as you mention, I mean how to get the URL of checkout, calling ShopifyCheckout. instance or ShopifyCheckout.instance.createCheckout has no webUrl?

**Comment by navidanchitrali** [comment]
@SimonIT  Dear sir, so far what i have understood from the function below, it adds the item to the checkout, which users have selected to buy, it returns and print me checkoutId successfully, and shopifyCheckout.checkoutLineItemsReplace(checkoutId, [variant.id]) mean add replace the item checkout with new one right?
![image](https://user-images.githubusercontent.com/48487470/136159379-69be8641-05f8-47c7-b2f0-826f48df8fbb.png)


1: what to pass this function when calling it?
2: what is _checkout, as you mention, I mean how to get the URL?
